services:
  # The Next.js Web App
  - type: web
    name: notes-web-app
    env: node
    rootDir: notes-app
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free


