import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';

// Auto-detect the notes directory
const getNotesDirectory = () => {
  const localPath = path.join(process.cwd(), '..', 'Generated-Notes');
  const prodPath = path.join(process.cwd(), 'public', 'data-notes');
  
  if (fs.existsSync(prodPath)) return prodPath;
  return localPath;
};

const notesDirectory = getNotesDirectory();

export interface NoteData {
  id: string;
  title: string;
  date: string;
  folder: string;
  readingTime: number;
  wordCount: number;
  headings: { text: string; level: number; slug: string }[];
  contentMarkdown?: string;
}

function calculateReadingTime(content: string): { readingTime: number; wordCount: number } {
  const plainText = content
    .replace(/```[\s\S]*?```/g, '')
    .replace(/[#*_~`>\-|]/g, '')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1');
  const words = plainText.split(/\s+/).filter((w) => w.length > 0);
  const wordCount = words.length;
  const readingTime = Math.max(1, Math.ceil(wordCount / 200));
  return { readingTime, wordCount };
}

function extractHeadings(content: string): { text: string; level: number; slug: string }[] {
  const headingRegex = /^(#{2,4})\s+(.+)$/gm;
  const headings: { text: string; level: number; slug: string }[] = [];
  let match;
  while ((match = headingRegex.exec(content)) !== null) {
    const text = match[2].replace(/[*_`]/g, '').trim();
    const slug = text
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-');
    headings.push({ text, level: match[1].length, slug });
  }
  return headings;
}

// Recursively find all markdown files
function getAllMarkdownFiles(dirPath: string, arrayOfFiles: string[] = []) {
  const files = fs.readdirSync(dirPath);

  files.forEach((file) => {
    // Skip the notes-app folder itself to avoid infinite loops, and skip standard ignores
    if (file === 'notes-app' || file === '.git' || file === 'node_modules' || file === 'scratch') {
      return;
    }

    const absolutePath = path.join(dirPath, file);
    if (fs.statSync(absolutePath).isDirectory()) {
      arrayOfFiles = getAllMarkdownFiles(absolutePath, arrayOfFiles);
    } else {
      // Only include .md files, and exclude the implementation plan/tasks generated by the AI
      if (file.endsWith('.md') && file !== 'implementation_plan.md' && file !== 'task.md' && file !== 'README.md') {
        arrayOfFiles.push(absolutePath);
      }
    }
  });

  return arrayOfFiles;
}

export function getSortedNotesData(): NoteData[] {
  const filePaths = getAllMarkdownFiles(notesDirectory);

  const allNotesData = filePaths.map((filePath) => {
    try {
      const relativePath = path.relative(notesDirectory, filePath);
      const id = relativePath.replace(/\.md$/, '').replace(/\\/g, '/');
      const folder = path.dirname(relativePath).replace(/\\/g, '/');
      const fileContents = fs.readFileSync(filePath, 'utf8');
      const matterResult = matter(fileContents);

      let title = matterResult.data.title;
      if (!title) {
        const h1Match = fileContents.match(/^#\s+(.*)/m);
        title = h1Match ? h1Match[1] : path.basename(filePath, '.md');
      }

      let date = matterResult.data.date;
      if (!date) {
        date = fs.statSync(filePath).birthtime.toISOString();
      }

      const { readingTime, wordCount } = calculateReadingTime(matterResult.content);

      return {
        id,
        title,
        date,
        folder,
        readingTime,
        wordCount,
        headings: [] as { text: string; level: number; slug: string }[],
      };
    } catch (error) {
      console.error(`Error parsing note: ${filePath}`, error);
      return null;
    }
  }).filter((note): note is NoteData => note !== null);

  return allNotesData.sort((a, b) => {
    if (a.date < b.date) return 1;
    return -1;
  });
}

export function getNoteData(id: string): NoteData {
  const fullPath = path.join(notesDirectory, `${id}.md`);
  const fileContents = fs.readFileSync(fullPath, 'utf8');
  const matterResult = matter(fileContents);

  let title = matterResult.data.title;
  if (!title) {
    const h1Match = fileContents.match(/^#\s+(.*)/m);
    title = h1Match ? h1Match[1] : path.basename(fullPath, '.md');
  }

  let date = matterResult.data.date;
  if (!date) {
    date = fs.statSync(fullPath).birthtime.toISOString();
  }

  const folder = path.dirname(id).replace(/\\/g, '/');
  const { readingTime, wordCount } = calculateReadingTime(matterResult.content);
  const headings = extractHeadings(matterResult.content);

  return {
    id,
    title,
    date,
    folder,
    readingTime,
    wordCount,
    headings,
    contentMarkdown: matterResult.content,
  };
}
