import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';

// The root of the MCA-notes workspace (one directory above the app)
const notesDirectory = path.join(process.cwd(), '..');

export interface NoteData {
  id: string; // The file path relative to root, minus the .md extension
  title: string;
  date: string;
  folder: string;
  contentMarkdown?: string;
}

// Recursively find all markdown files
function getAllMarkdownFiles(dirPath: string, arrayOfFiles: string[] = []) {
  const files = fs.readdirSync(dirPath);

  files.forEach((file) => {
    // Skip the notes-app folder itself to avoid infinite loops, and skip standard ignores
    if (file === 'notes-app' || file === '.git' || file === 'node_modules' || file === 'scratch') {
      return;
    }

    const absolutePath = path.join(dirPath, file);
    if (fs.statSync(absolutePath).isDirectory()) {
      arrayOfFiles = getAllMarkdownFiles(absolutePath, arrayOfFiles);
    } else {
      // Only include .md files, and exclude the implementation plan/tasks generated by the AI
      if (file.endsWith('.md') && file !== 'implementation_plan.md' && file !== 'task.md' && file !== 'README.md') {
        arrayOfFiles.push(absolutePath);
      }
    }
  });

  return arrayOfFiles;
}

export function getSortedNotesData(): NoteData[] {
  const filePaths = getAllMarkdownFiles(notesDirectory);
  
  const allNotesData = filePaths.map((filePath) => {
    // Create an id based on the relative path
    const relativePath = path.relative(notesDirectory, filePath);
    const id = relativePath.replace(/\.md$/, '').replace(/\\/g, '/'); // Normalize slashes for URLs
    
    // Extract the folder name
    const folder = path.dirname(relativePath).replace(/\\/g, '/');
    
    // Read file as string
    const fileContents = fs.readFileSync(filePath, 'utf8');

    // Use gray-matter to parse the post metadata section
    const matterResult = matter(fileContents);

    // If there is no frontmatter title, extract an H1 or use the filename
    let title = matterResult.data.title;
    if (!title) {
        const h1Match = fileContents.match(/^#\s+(.*)/m);
        title = h1Match ? h1Match[1] : path.basename(filePath, '.md');
    }

    // Attempt to extract a date from frontmatter, otherwise use file creation time
    let date = matterResult.data.date;
    if (!date) {
        date = fs.statSync(filePath).birthtime.toISOString();
    }

    return {
      id,
      title,
      date,
      folder,
    };
  });

  // Sort notes by date (newest first)
  return allNotesData.sort((a, b) => {
    if (a.date < b.date) {
      return 1;
    } else {
      return -1;
    }
  });
}

export function getNoteData(id: string): NoteData {
  const fullPath = path.join(notesDirectory, `${id}.md`);
  const fileContents = fs.readFileSync(fullPath, 'utf8');

  const matterResult = matter(fileContents);

  let title = matterResult.data.title;
  if (!title) {
      const h1Match = fileContents.match(/^#\s+(.*)/m);
      title = h1Match ? h1Match[1] : path.basename(fullPath, '.md');
  }

  let date = matterResult.data.date;
  if (!date) {
      date = fs.statSync(fullPath).birthtime.toISOString();
  }

  const folder = path.dirname(id).replace(/\\/g, '/');

  return {
    id,
    title,
    date,
    folder,
    contentMarkdown: matterResult.content,
  };
}
